services:
  # Spark Master
  spark-master:
    container_name: spark-master
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_METRICS_ENABLED=true
      - SPARK_USER=spark
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j2.properties
      - PYTHONPATH=/opt/bitnami/spark/jobs/app:/opt/bitnami/spark/jobs/app/
    ports:
      - "8080:8080"
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
      - ${APP_METRICS_PATH}:/opt/bitnami/spark/metrics

    # Spark Workers
  spark-worker-1:
    container_name: spark-worker-1
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j2.properties
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
      - ${APP_METRICS_PATH}:/opt/bitnami/spark/metrics
    depends_on:
      - spark-master

  spark-worker-2:
    container_name: spark-worker-2
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j2.properties
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
      - ${APP_METRICS_PATH}:/opt/bitnami/spark/metrics
    depends_on:
      - spark-master

  spark-worker-3:
    container_name: spark-worker-3
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j2.properties
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
      - ${APP_METRICS_PATH}:/opt/bitnami/spark/metrics
    depends_on:
      - spark-master

